In [4]:
!pip install pandas numpy openpyxl sqlalchemy pymysql

Requirement already satisfied: pandas in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.5.3)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: sqlalchemy in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.0.54)
Collecting pymysql
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.4)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: greenlet>=1 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (3.5.6)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: pymysql, et-xmlfile, openpyxl

   ---------------------------------------- 0/3 [pymysql]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   ---------------------------------------- 3/3 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5 pymysql-1.2.3

In [2]:
import pandas as pd
import numpy as np

In [6]:
file_path = r"C:\Users\esk06\Downloads\archive\Electronic_sales_Sep2023-Sep2024.csv"

In [7]:
df = pd.read_csv(file_path)

In [8]:
df.head()

,Customer ID,Age,Gender,Loyalty Member,Product Type,SKU,Rating,Order Status,Payment Method,Total Price,Unit Price,Quantity,Purchase Date,Shipping Type,Add-ons Purchased,Add-on Total
0,1000,53,Male,No,Smartphone,SKU1004,2,Cancelled,Credit Card,5538.33,791.19,7,2024-03-20,Standard,"Accessory,Accessory,Accessory",40.21
1,1000,53,Male,No,Tablet,SKU1002,3,Completed,Paypal,741.09,247.03,3,2024-04-20,Overnight,Impulse Item,26.09
2,1002,41,Male,No,Laptop,SKU1005,3,Completed,Credit Card,1855.84,463.96,4,2023-10-17,Express,NaN,0.00
3,1002,41,Male,Yes,Smartphone,SKU1004,2,Completed,Cash,3164.76,791.19,4,2024-08-09,Overnight,"Impulse Item,Impulse Item",60.16
4,1003,75,Male,Yes,Smartphone,SKU1001,5,Completed,Cash,41.50,20.75,2,2024-05-21,Express,Accessory,35.56

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer ID        20000 non-null  int64
 1   Age                20000 non-null  int64
 2   Gender             19999 non-null  str
 3   Loyalty Member     20000 non-null  str
 4   Product Type       20000 non-null  str
 5   SKU                20000 non-null  str
 6   Rating             20000 non-null  int64
 7   Order Status       20000 non-null  str
 8   Payment Method     20000 non-null  str
 9   Total Price        20000 non-null  float64
 10  Unit Price         20000 non-null  float64
 11  Quantity           20000 non-null  int64
 12  Purchase Date      20000 non-null  str
 13  Shipping Type      20000 non-null  str
 14  Add-ons Purchased  15132 non-null  str
 15  Add-on Total       20000 non-null  float64
dtypes: float64(3), int64(4), str(9)
memory usage: 2.4 MB

In [10]:
df.shape

(20000, 16)

In [12]:
df.isnull().sum()

Customer ID             0
Age                     0
Gender                  1
Loyalty Member          0
Product Type            0
SKU                     0
Rating                  0
Order Status            0
Payment Method          0
Total Price             0
Unit Price              0
Quantity                0
Purchase Date           0
Shipping Type           0
Add-ons Purchased    4868
Add-on Total            0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.dtypes

Customer ID            int64
Age                    int64
Gender                   str
Loyalty Member           str
Product Type             str
SKU                      str
Rating                 int64
Order Status             str
Payment Method           str
Total Price          float64
Unit Price           float64
Quantity               int64
Purchase Date            str
Shipping Type            str
Add-ons Purchased        str
Add-on Total         float64
dtype: object

In [15]:
df.columns.tolist()

['Customer ID',
 'Age',
 'Gender',
 'Loyalty Member',
 'Product Type',
 'SKU',
 'Rating',
 'Order Status',
 'Payment Method',
 'Total Price',
 'Unit Price',
 'Quantity',
 'Purchase Date',
 'Shipping Type',
 'Add-ons Purchased',
 'Add-on Total']

In [16]:
df= df.drop_duplicates()

In [17]:
df.replace(['#N/A',''],np.nan,inplace=True)

,Customer ID,Age,Gender,Loyalty Member,Product Type,SKU,Rating,Order Status,Payment Method,Total Price,Unit Price,Quantity,Purchase Date,Shipping Type,Add-ons Purchased,Add-on Total
0,1000,53,Male,No,Smartphone,SKU1004,2,Cancelled,Credit Card,5538.33,791.19,7,2024-03-20,Standard,"Accessory,Accessory,Accessory",40.21
1,1000,53,Male,No,Tablet,SKU1002,3,Completed,Paypal,741.09,247.03,3,2024-04-20,Overnight,Impulse Item,26.09
2,1002,41,Male,No,Laptop,SKU1005,3,Completed,Credit Card,1855.84,463.96,4,2023-10-17,Express,NaN,0.00
3,1002,41,Male,Yes,Smartphone,SKU1004,2,Completed,Cash,3164.76,791.19,4,2024-08-09,Overnight,"Impulse Item,Impulse Item",60.16
4,1003,75,Male,Yes,Smartphone,SKU1001,5,Completed,Cash,41.50,20.75,2,2024-05-21,Express,Accessory,35.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,27,Female,No,Smartphone,SMP234,4,Completed,Bank Transfer,6838.08,1139.68,6,2024-06-15,Expedited,NaN,0.00
19996,19996,27,Female,Yes,Laptop,LTP123,4,Cancelled,Credit Card,2697.28,674.32,4,2024-07-18,Standard,NaN,0.00
19997,19996,27,Female,No,Headphones,HDP456,4,Completed,Bank Transfer,1805.90,361.18,5,2024-08-26,Standard,"Impulse Item, Extended Warranty, Accessory",198.98
19998,19997,27,Male,No,Headphones,HDP456,1,Cancelled,Bank Transfer,2528.26,361.18,7,2024-01-06,Expedited,"Extended Warranty, Accessory",101.34
19999,19998,27,NaN,Yes,Laptop,LTP123,4,Completed,Bank Transfer,674.32,674.32,1,2024-01-29,Expedited,NaN,0.00

In [19]:
df= df.loc[:, df.isnull().mean() <0.5]

In [20]:
df.head()

,Customer ID,Age,Gender,Loyalty Member,Product Type,SKU,Rating,Order Status,Payment Method,Total Price,Unit Price,Quantity,Purchase Date,Shipping Type,Add-ons Purchased,Add-on Total
0,1000,53,Male,No,Smartphone,SKU1004,2,Cancelled,Credit Card,5538.33,791.19,7,2024-03-20,Standard,"Accessory,Accessory,Accessory",40.21
1,1000,53,Male,No,Tablet,SKU1002,3,Completed,Paypal,741.09,247.03,3,2024-04-20,Overnight,Impulse Item,26.09
2,1002,41,Male,No,Laptop,SKU1005,3,Completed,Credit Card,1855.84,463.96,4,2023-10-17,Express,NaN,0.00
3,1002,41,Male,Yes,Smartphone,SKU1004,2,Completed,Cash,3164.76,791.19,4,2024-08-09,Overnight,"Impulse Item,Impulse Item",60.16
4,1003,75,Male,Yes,Smartphone,SKU1001,5,Completed,Cash,41.50,20.75,2,2024-05-21,Express,Accessory,35.56

In [22]:
df =df.apply(lambda x: x.str.strip() if x.dtype =='object' else x)

In [24]:
df['Age'].fillna(df['Age'].median(), inplace = True)

C:\Users\esk06\AppData\Local\Temp\ipykernel_12860\3612560828.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'].fillna(df['Age'].median(), inplace = True)

0        53
1        53
2        41
3        41
4        75
         ..
19995    27
19996    27
19997    27
19998    27
19999    27
Name: Age, Length: 20000, dtype: int64

In [25]:
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

In [26]:
df.head()

,Customer ID,Age,Gender,Loyalty Member,Product Type,SKU,Rating,Order Status,Payment Method,Total Price,Unit Price,Quantity,Purchase Date,Shipping Type,Add-ons Purchased,Add-on Total
0,1000,53,Male,No,Smartphone,SKU1004,2,Cancelled,Credit Card,5538.33,791.19,7,2024-03-20,Standard,"Accessory,Accessory,Accessory",40.21
1,1000,53,Male,No,Tablet,SKU1002,3,Completed,Paypal,741.09,247.03,3,2024-04-20,Overnight,Impulse Item,26.09
2,1002,41,Male,No,Laptop,SKU1005,3,Completed,Credit Card,1855.84,463.96,4,2023-10-17,Express,NaN,0.00
3,1002,41,Male,Yes,Smartphone,SKU1004,2,Completed,Cash,3164.76,791.19,4,2024-08-09,Overnight,"Impulse Item,Impulse Item",60.16
4,1003,75,Male,Yes,Smartphone,SKU1001,5,Completed,Cash,41.50,20.75,2,2024-05-21,Express,Accessory,35.56

In [27]:
df['Purchase Date'] = pd.to_datetime(df['Purchase Date'],errors = 'coerce')

In [28]:
df.dtypes

Customer ID                   int64
Age                           int64
Gender                          str
Loyalty Member                  str
Product Type                    str
SKU                             str
Rating                        int64
Order Status                    str
Payment Method                  str
Total Price                 float64
Unit Price                  float64
Quantity                      int64
Purchase Date        datetime64[us]
Shipping Type                   str
Add-ons Purchased               str
Add-on Total                float64
dtype: object

In [30]:
cols = ['Age','Rating','Total Price','Unit Price','Quantity','Add-on Total']

for c in cols:
    df[c]=pd.to_numeric(df[c],errors = 'coerce')

In [31]:
df.head()

,Customer ID,Age,Gender,Loyalty Member,Product Type,SKU,Rating,Order Status,Payment Method,Total Price,Unit Price,Quantity,Purchase Date,Shipping Type,Add-ons Purchased,Add-on Total
0,1000,53,Male,No,Smartphone,SKU1004,2,Cancelled,Credit Card,5538.33,791.19,7,2024-03-20,Standard,"Accessory,Accessory,Accessory",40.21
1,1000,53,Male,No,Tablet,SKU1002,3,Completed,Paypal,741.09,247.03,3,2024-04-20,Overnight,Impulse Item,26.09
2,1002,41,Male,No,Laptop,SKU1005,3,Completed,Credit Card,1855.84,463.96,4,2023-10-17,Express,NaN,0.00
3,1002,41,Male,Yes,Smartphone,SKU1004,2,Completed,Cash,3164.76,791.19,4,2024-08-09,Overnight,"Impulse Item,Impulse Item",60.16
4,1003,75,Male,Yes,Smartphone,SKU1001,5,Completed,Cash,41.50,20.75,2,2024-05-21,Express,Accessory,35.56

In [32]:
df  = df[df['Quantity']> 0]

In [33]:
df['Sales Revenue'] = df['Total Price'] + df['Add-on Total']

In [36]:
df.head()

,Customer ID,Age,Gender,Loyalty Member,Product Type,SKU,Rating,Order Status,Payment Method,Total Price,Unit Price,Quantity,Purchase Date,Shipping Type,Add-ons Purchased,Add-on Total,Sales Revenue
0,1000,53,Male,No,Smartphone,SKU1004,2,Cancelled,Credit Card,5538.33,791.19,7,2024-03-20,Standard,"Accessory,Accessory,Accessory",40.21,5578.54
1,1000,53,Male,No,Tablet,SKU1002,3,Completed,Paypal,741.09,247.03,3,2024-04-20,Overnight,Impulse Item,26.09,767.18
2,1002,41,Male,No,Laptop,SKU1005,3,Completed,Credit Card,1855.84,463.96,4,2023-10-17,Express,NaN,0.00,1855.84
3,1002,41,Male,Yes,Smartphone,SKU1004,2,Completed,Cash,3164.76,791.19,4,2024-08-09,Overnight,"Impulse Item,Impulse Item",60.16,3224.92
4,1003,75,Male,Yes,Smartphone,SKU1001,5,Completed,Cash,41.50,20.75,2,2024-05-21,Express,Accessory,35.56,77.06

In [37]:
df['Order ID'] = range(1,len(df)+1)

In [38]:
df['Year'] = df['Purchase Date'].dt.year

In [40]:
df['Day'] = df['Purchase Date'].dt.day_name()

In [41]:
df['Month'] = df['Purchase Date'].dt.month_name()

In [42]:
df.head()

,Customer ID,Age,Gender,Loyalty Member,Product Type,SKU,Rating,Order Status,Payment Method,Total Price,...,Quantity,Purchase Date,Shipping Type,Add-ons Purchased,Add-on Total,Sales Revenue,Order ID,Year,Day,Month
0,1000,53,Male,No,Smartphone,SKU1004,2,Cancelled,Credit Card,5538.33,...,7,2024-03-20,Standard,"Accessory,Accessory,Accessory",40.21,5578.54,1,2024,Wednesday,March
1,1000,53,Male,No,Tablet,SKU1002,3,Completed,Paypal,741.09,...,3,2024-04-20,Overnight,Impulse Item,26.09,767.18,2,2024,Saturday,April
2,1002,41,Male,No,Laptop,SKU1005,3,Completed,Credit Card,1855.84,...,4,2023-10-17,Express,NaN,0.00,1855.84,3,2023,Tuesday,October
3,1002,41,Male,Yes,Smartphone,SKU1004,2,Completed,Cash,3164.76,...,4,2024-08-09,Overnight,"Impulse Item,Impulse Item",60.16,3224.92,4,2024,Friday,August
4,1003,75,Male,Yes,Smartphone,SKU1001,5,Completed,Cash,41.50,...,2,2024-05-21,Express,Accessory,35.56,77.06,5,2024,Tuesday,May

In [45]:
bins = [17,35,55,75,np.inf]
labels = ['18-35','36-55','56-75','75+']

df['Age-Group'] = pd.cut(df['Age'],bins=bins,labels=labels)

In [46]:
df.head()

,Customer ID,Age,Gender,Loyalty Member,Product Type,SKU,Rating,Order Status,Payment Method,Total Price,...,Purchase Date,Shipping Type,Add-ons Purchased,Add-on Total,Sales Revenue,Order ID,Year,Day,Month,Age-Group
0,1000,53,Male,No,Smartphone,SKU1004,2,Cancelled,Credit Card,5538.33,...,2024-03-20,Standard,"Accessory,Accessory,Accessory",40.21,5578.54,1,2024,Wednesday,March,36-55
1,1000,53,Male,No,Tablet,SKU1002,3,Completed,Paypal,741.09,...,2024-04-20,Overnight,Impulse Item,26.09,767.18,2,2024,Saturday,April,36-55
2,1002,41,Male,No,Laptop,SKU1005,3,Completed,Credit Card,1855.84,...,2023-10-17,Express,NaN,0.00,1855.84,3,2023,Tuesday,October,36-55
3,1002,41,Male,Yes,Smartphone,SKU1004,2,Completed,Cash,3164.76,...,2024-08-09,Overnight,"Impulse Item,Impulse Item",60.16,3224.92,4,2024,Friday,August,36-55
4,1003,75,Male,Yes,Smartphone,SKU1001,5,Completed,Cash,41.50,...,2024-05-21,Express,Accessory,35.56,77.06,5,2024,Tuesday,May,56-75

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer ID        20000 non-null  int64
 1   Age                20000 non-null  int64
 2   Gender             20000 non-null  str
 3   Loyalty Member     20000 non-null  str
 4   Product Type       20000 non-null  str
 5   SKU                20000 non-null  str
 6   Rating             20000 non-null  int64
 7   Order Status       20000 non-null  str
 8   Payment Method     20000 non-null  str
 9   Total Price        20000 non-null  float64
 10  Unit Price         20000 non-null  float64
 11  Quantity           20000 non-null  int64
 12  Purchase Date      20000 non-null  datetime64[us]
 13  Shipping Type      20000 non-null  str
 14  Add-ons Purchased  15132 non-null  str
 15  Add-on Total       20000 non-null  float64
 16  Sales Revenue      20000 non-null  float64
 17  Order ID           20000 non-null  int64
 18  Year               20000 non-null  int32
 19  Day                20000 non-null  str
 20  Month              20000 non-null  str
 21  Age-Group          20000 non-null  category
dtypes: category(1), datetime64[us](1), float64(4), int32(1), int64(5), str(10)
memory usage: 3.1 MB

In [52]:
df.isnull().sum()

Customer ID             0
Age                     0
Gender                  0
Loyalty Member          0
Product Type            0
SKU                     0
Rating                  0
Order Status            0
Payment Method          0
Total Price             0
Unit Price              0
Quantity                0
Purchase Date           0
Shipping Type           0
Add-ons Purchased    4868
Add-on Total            0
Sales Revenue           0
Order ID                0
Year                    0
Day                     0
Month                   0
Age-Group               0
dtype: int64

In [55]:
df.to_csv(r'C:\Users\esk06\Downloads\archive\electronic_Sales_data.csv',index=False)

In [5]:
from sqlalchemy import create_engine
engine = create_engine('mysql+pymysql://root:jhilik%04111@localhost/electronics')

In [14]:
df.to_sql(
    name = 'order',
    con = engine,
    if_exists = 'replace',
    index = False
)

NameError: name 'df' is not defined

In [10]:
import pandas as pd
import numpy as np

In [22]:
file_path = r"C:\\Users\\esk06\\Downloads\\archive\\electronic_Sales_data.csv"

In [23]:
df = pd.read_csv(file_path)

In [28]:
from sqlalchemy import create_engine
engine = create_engine('mysql+pymysql://root:jhilika%40111@localhost/electronics')

In [ ]:
from urllib.parse import quote_plus
from sqlalchemy import create_engine

password = quote_plus("jhilik@111")
engine = create_engine(f"mysql+pymysql://root:{password}@localhost/electronics")

In [32]:
df.to_sql(
    name = 'orders',
    con = engine,
    if_exists = 'replace',
    index = False
)

20000